Updated and fixed ZMX Metric Reference docs.
zio/zio-metrics-connectors pull request #43
Opened 2023-05-28 23:14 UTC by Grryum

Made docs up to date according to latest ZIO Metric API

2023-05-28 23:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/zio/zio-metrics-connectors?pullRequest=43) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/zio/zio-metrics-connectors?pullRequest=43) before we can accept your contribution.<br/><hr/>**Vladislav Ugryumov** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/zio/zio-metrics-connectors?pullRequest=43) it.</sub>

2023-06-07 21:09 UTC, petoalbert requested changes
Thank you @Grryum for these changes. I left a few minor comments, otherwise everything looks good. Could you please sign the CLA as well?

2023-06-07 21:09 UTC, petoalbert commented on docs/metrics/zmx-metric-reference.md
> +Also, every `Metric`s implementation (kind of metric) are further qualified by a type parameter `In` that must be
What did you mean by "(kind of metric)" here? Can we remove it?

2023-06-07 21:09 UTC, petoalbert commented on docs/metrics/zmx-metric-reference.md
> +There is also an ability to setting up additional conditions for metric value capture.
I believe the correct grammatical way would be to write "to set up" instead of "to setting up".

2023-06-07 21:09 UTC, petoalbert commented on docs/metrics/zmx-metric-reference.md
> +Now we can apply these effects to effects having an output type `Double`. Note that we can instrument
I think it should be "apply these aspects to effects".

2023-06-07 21:55 UTC, Grryum commented
@petoalbert thank you for your review! I fixed typos and removed any ZMX reference from this part of doc as we discussed with @adamgfraser in a Discord.
I suppose that ZMX references should also be removed from other parts of doc.
I could do it in this PR or in another one.

2023-06-08 09:19 UTC, petoalbert commented
Thank you @Grryum . If you could rename all the other ZMX references in this PR, that would be nice.

2023-06-20 23:09 UTC, Grryum commented
@petoalbert I tried to remove all ZMX references from docs and sources. Also tried to actualize samples.
I did not touch main README.md and could not recreate some of screenshots with ZMX references. Don't know if it matters.
Please check it out.
@calvinlfer your turn :)

2023-06-25 10:58 UTC, petoalbert commented
Thank you @Grryum! I think the README needs a significant update anyway, so we can do that later.

2023-06-25 10:59 UTC, petoalbert approved these changes

2023-06-25 10:59 UTC, merged